### ISSUE TITLE
ServerEvaluationCall eval method throws exception when handling JS variables having null

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#317]
ServerEvaluationCall eval method throws exception when a JavaScript variable holds a null value.
For example, in the case following code snippet: 

addVariableAs("myJsonNull",new ObjectMapper().createObjectNode().nullNode()

When doing an eval() with the script the getJsonType method thows IllegalArgumentException with the message 
"When using JacksonHandle or JacksonParserHandle with ServerEvaluationCall the content must be 
a valid array or object"

Here is the test method that fails. Refer to test-complete's TestEvalJavaScript 

public void testJSDifferentVariableTypes() throws Exception {	
		DocumentBuilder db = DocumentBuilderFactory.newInstance().newDocumentBuilder();
		InputSource is = new InputSource();
		is.setCharacterStream(new StringReader("<foo attr=\"attribute\"><?processing instruction?>test1</foo>"));
		Document doc = db.parse(is);
		String jsonNode = "{ \"a\" : {\"obj\": \"value\"}, \"b\" : \"s0\",\"c1\" : 1,\"c2\" : 2,\"d\" : null,\"f\" : true,\"g\" : [\"s1\", \"s2\", \"s3\" ]}";
	    System.out.println(this.convertXMLDocumentToString(doc));
	 	try{
		String query1 = " var results = [];"
						+"var myString;"
						+"var myBool ;"
						+"var myInteger;"
						+"var myDecimal;"
						+"var myJsonObject;"
						+"var myNull;"
						+ "var myJsonArray;"
						+ "var myJsonNull;"
						+ "results.push(myString,myBool,myInteger,myDecimal,myJsonObject,myJsonArray,myNull,myJsonNull);"
						+"xdmp.arrayValues(results)";
		
		ServerEvaluationCall evl= client.newServerEval().javascript(query1);
		evl.addVariable("myString", "xml")
		.addVariable("myBool", true)
		.addVariable("myInteger", (int)31)
		.addVariable("myDecimal", (double)1.0471975511966)
		.addVariableAs("myJsonObject",new ObjectMapper().createObjectNode().put("foo", "v1").putNull("testNull"))
		.addVariableAs("myNull",(String) null)
		.addVariableAs("myJsonArray",new ObjectMapper().createArrayNode().add(1).add(2).add(3))
		.addVariableAs("myJsonNull",new ObjectMapper().createObjectNode().nullNode() )
		;
		System.out.println(new ObjectMapper().createObjectNode().nullNode().toString());
		EvalResultIterator evr = evl.eval();
		this.validateReturnTypes(evr);
		
	}catch(Exception e){
		throw e;
	}
	}

**Comment by sammefford** [comment]
We'll continue to give you the error "When using JacksonHandle or JacksonParserHandle with ServerEvaluationCall the content must be a valid array or object" if you pass a NullNode object, since we don't support that type of stand-alone JSON object, we only support JSON null in the context of an ArrayNode or ObjectNode.  

However, I agree that we should allow null values to addVariableAs so you can set values that are occasionally null without getting the IllegalStateException("null values not currently supported, but your variable {name} has a null value").  I'll keep this bug open so I can get rid of that error and allow null values.

**Comment by sammefford** [comment]
Ok, this is implemented and pushed to github.  But it's not working currently because of what seems to be a bug in an underlying layer.  I'll wait until that's resolved, then confirm this works, then assign to you, Ajit.

**Comment by sammefford** [comment]
I misunderstood the underlying layer.  I believe I've fixed this to work as it should.  I also added more tests.

**Comment by georgeajit** [comment]
Pulled the latest from Git and ran the test on MarkLogic Server Build 8.0 dated 0827. The issue is not fixed. 
Here is the client's exception trace.

```
java.lang.IllegalArgumentException: When using JacksonHandle or JacksonParserHandle with ServerEvaluationCall the content must be a valid array or object
	at com.marklogic.client.impl.JerseyServices.getJsonType(JerseyServices.java:3977)
	at com.marklogic.client.impl.JerseyServices.postEvalInvoke(JerseyServices.java:3914)
	at com.marklogic.client.impl.ServerEvaluationCallImpl.eval(ServerEvaluationCallImpl.java:163)
	at com.marklogic.client.functionaltest.TestEvalJavaScript.testJSDifferentVariableTypes(TestEvalJavaScript.java:403)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

```

**Comment by sammefford** [comment]
This is expected behavior.  Please see my comment on July 7: https://github.com/marklogic/java-client-api/issues/317#issuecomment-119374877

**Comment by georgeajit** [comment]
Fixed test.
